# Generated by Django 4.1.2 on 2023-01-12 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cfaa79fa-0e5a-45a5-b084-b9f61388e708'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
